# -*- coding: utf-8 -*-
"""Stackoverflow Annual Developers Survey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pb4wdlVKek7AsuQobO_jDqUEWP7LmWOH

**STACK OVERFLOW DEVELOPERS SURVEY 2023 ANALYTICAL PROJECT**

Project Title: Decoding the Global Developers Ecosystem: Insights from the Stack Overflow Developer Survey 2023

Core Objective:
Analyze the Stack overflow Developers Survey 2023 to uncover meaningful insights about the following:
1. Who are the developers?
2. How do developers learn?
3. What are the most popular technologies?
4. What technologies do they aspire to use?
5. What factors influences the annual compensation?
6. How AI is changing development
7. What are the trends in the future?

**SECTION A: DATA UNDERSTANDING**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import regex
import re
import os
os.makedirs('plots', exist_ok=True)

df=pd.read_csv('survey_results_public.csv')

"""**SECTION B — Data Understanding**

DATA DICTIONARY & COLOUMN THEMES

DEMOGRAPHICS:                  
1. ResponseID
2. Age
3. Employment
4. EdLevel
5. Country

CAREER & EXPERIENCE:
1. YearsCode
2. YearsCodePro
3. OrgSize
4. WorkExp
5. Industry

COMPENSATION:
1. Currency
2. CompTotal
3. ConvertedCompYearly

TECHNOLOGY USAGE:
1. LanguageHaveWorkedWith
2. LanguageWantToWorkWith
3. DatabaseHaveWorkedWith
4. DatabaseWantToWorkWith
5. PlatformHaveWorkedWith
6. PlatformWantToWorkWith
7. WebframeHaveWorkedWith
8. WebframeWantToWorkWith
9. MiscTechHaveWorkedWith
10. MiscTechWantToWorkWith

LEARNING PATHWAYS:
1. LearnCode
2. LearnCodeOnline
3. LearnCodeCoursesCert

WORKING STYPlE:
1. RemoteWork

AI & COMMPUNITY:
1. SOAI-
2. AISelect-Do you currently use AI tools in your development process?
3. AISent - How favorable is your stance on using AI tools as part of your development workflow?
4. AIBen - How much do you trust the accuracy of the output from AI tools as part of your development workflow?



These are some of the themes based on the column types. This is done to have a clear understanding column types and which columns are important in analysis and to better structure the pipeline.

**SECTION C - Data Cleaning & Preparation**
"""

#1. Standardize Column names
""" Converting all the column names to standard snake_case representation"""

df.columns=(df.columns.str.replace('(?<=[a-z])(?=[A-Z])', '_', regex=True).str.lower())

#2. Missing Value Analysis
missing_info=pd.DataFrame({"Column Name":df.columns,'Missing Count':df.isnull().sum(),
              'Missing Percentage': (df.isnull().sum() / len(df)) * 100})
missing_info.sort_values(by='Missing Percentage', ascending=False)

"""The columns related to AI show the highest proportion of missing values in the dataset. This is likely because these questions were optional, not relevant to all respondents, or skipped during survey completion. Since the top five AI-related columns each contain more than 90% missing values, they are not suitable for broad population-level analysis in their current form."""

#3. Clean Special Categorical Value
""" Some columns have values that are not in numerical form
Which means we have to covert them into numerical data"""

def clean_special_values(val):
  if pd.isna(val):
    return val
  elif val=='Less than 1 year':
    return 0.5
  elif val=='More than 50 years':
    return 51
  else:
    return val


df['years_code']=df['years_code'].apply(clean_special_values)
df['years_code_pro']=df['years_code_pro'].apply(clean_special_values)

"""The columns such as *years_code, years_code_pro* contains values such as *less than 1 year and more than 50 years* which needed to be converted into 0.5 and 52 years respectively

**Data Preparation**


Creating derived features from existing columns: This is done by creating experience bands, salary ranges, region, and respondent category
"""

#Region mapping dictionary

#These are hard coded for now. Will use specific packages in the next versions

region_map = {

    # North America
    'United States of America': 'North America',
    'Canada': 'North America',
    'Mexico': 'North America',
    'Guatemala': 'North America',
    'Belize': 'North America',
    'El Salvador': 'North America',
    'Honduras': 'North America',
    'Nicaragua': 'North America',
    'Costa Rica': 'North America',
    'Panama': 'North America',
    'Cuba': 'North America',
    'Jamaica': 'North America',
    'Dominican Republic': 'North America',
    'Barbados': 'North America',
    'Trinidad and Tobago': 'North America',
    'Saint Vincent and the Grenadines': 'North America',
    'Grenada': 'North America',
    'Antigua and Barbuda': 'North America',

    # South America
    'Brazil': 'South America',
    'Argentina': 'South America',
    'Chile': 'South America',
    'Colombia': 'South America',
    'Peru': 'South America',
    'Uruguay': 'South America',
    'Paraguay': 'South America',
    'Bolivia': 'South America',
    'Ecuador': 'South America',
    'Venezuela, Bolivarian Republic of...': 'South America',

    # Europe
    'United Kingdom of Great Britain and Northern Ireland': 'Europe',
    'Germany': 'Europe',
    'France': 'Europe',
    'Netherlands': 'Europe',
    'Finland': 'Europe',
    'Sweden': 'Europe',
    'Spain': 'Europe',
    'Belgium': 'Europe',
    'Italy': 'Europe',
    'Portugal': 'Europe',
    'Poland': 'Europe',
    'Switzerland': 'Europe',
    'Austria': 'Europe',
    'Denmark': 'Europe',
    'Norway': 'Europe',
    'Ireland': 'Europe',
    'Romania': 'Europe',
    'Czech Republic': 'Europe',
    'Slovakia': 'Europe',
    'Hungary': 'Europe',
    'Croatia': 'Europe',
    'Serbia': 'Europe',
    'Slovenia': 'Europe',
    'Luxembourg': 'Europe',
    'Lithuania': 'Europe',
    'Latvia': 'Europe',
    'Estonia': 'Europe',
    'Bulgaria': 'Europe',
    'Greece': 'Europe',
    'Albania': 'Europe',
    'Cyprus': 'Europe',
    'Malta': 'Europe',
    'Kosovo': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'Montenegro': 'Europe',
    'Iceland': 'Europe',
    'Belarus': 'Europe',
    'Ukraine': 'Europe',
    'Republic of Moldova': 'Europe',
    'Russian Federation': 'Europe',
    'Andorra': 'Europe',
    'Isle of Man': 'Europe',
    'The former Yugoslav Republic of Macedonia': 'Europe',

    # Asia
    'India': 'Asia',
    'China': 'Asia',
    'Japan': 'Asia',
    'Pakistan': 'Asia',
    'Bangladesh': 'Asia',
    'Sri Lanka': 'Asia',
    'Nepal': 'Asia',
    'Singapore': 'Asia',
    'Malaysia': 'Asia',
    'Indonesia': 'Asia',
    'Philippines': 'Asia',
    'Thailand': 'Asia',
    'Viet Nam': 'Asia',
    'Republic of Korea': 'Asia',
    'South Korea': 'Asia',
    'North Korea': 'Asia',
    'Taiwan': 'Asia',
    'Hong Kong (S.A.R.)': 'Asia',
    'United Arab Emirates': 'Asia',
    'Saudi Arabia': 'Asia',
    'Qatar': 'Asia',
    'Bahrain': 'Asia',
    'Oman': 'Asia',
    'Kuwait': 'Asia',
    'Israel': 'Asia',
    'Turkey': 'Asia',
    'Iran, Islamic Republic of...': 'Asia',
    'Iraq': 'Asia',
    'Jordan': 'Asia',
    'Lebanon': 'Asia',
    'Palestine': 'Asia',
    'Afghanistan': 'Asia',
    'Kazakhstan': 'Asia',
    'Uzbekistan': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Tajikistan': 'Asia',
    'Turkmenistan': 'Asia',
    'Armenia': 'Asia',
    'Azerbaijan': 'Asia',
    'Georgia': 'Asia',
    'Bhutan': 'Asia',
    'Cambodia': 'Asia',
    "Lao People's Democratic Republic": 'Asia',
    'Myanmar': 'Asia',
    'Maldives': 'Asia',
    'Mongolia': 'Asia',
    'Brunei Darussalam': 'Asia',

    # Africa
    'Nigeria': 'Africa',
    'South Africa': 'Africa',
    'Egypt': 'Africa',
    'Kenya': 'Africa',
    'Morocco': 'Africa',
    'Tunisia': 'Africa',
    'Algeria': 'Africa',
    'Ethiopia': 'Africa',
    'Ghana': 'Africa',
    'Uganda': 'Africa',
    'Zimbabwe': 'Africa',
    'Zambia': 'Africa',
    'Mauritius': 'Africa',
    'Cameroon': 'Africa',
    'Mozambique': 'Africa',
    'Somalia': 'Africa',
    'Rwanda': 'Africa',
    'Senegal': 'Africa',
    "Côte d'Ivoire": 'Africa',
    'Malawi': 'Africa',
    'Sierra Leone': 'Africa',
    'Guinea': 'Africa',
    'Mali': 'Africa',
    'Botswana': 'Africa',
    'Liberia': 'Africa',
    'Madagascar': 'Africa',
    'Niger': 'Africa',
    'Angola': 'Africa',
    'Benin': 'Africa',
    'Djibouti': 'Africa',
    'Gabon': 'Africa',
    'Burkina Faso': 'Africa',
    'Lesotho': 'Africa',
    'Mauritania': 'Africa',
    'Democratic Republic of the Congo': 'Africa',
    'Congo, Republic of the...': 'Africa',
    'Libyan Arab Jamahiriya': 'Africa',
    'Swaziland': 'Africa',
    'United Republic of Tanzania': 'Africa',

    # Oceania
    'Australia': 'Oceania',
    'New Zealand': 'Oceania',
    'Fiji': 'Oceania',
    'Palau': 'Oceania',

    # Other
    'Nomadic': 'Other'
}





# Create region column
df['region'] = df['country'].map(region_map).fillna('Other')

#---------------------------------------------------------------#
#These are helper functions used to create bins for exp and sal.
#---------------------------------------------------------------#


# Experince band
def exp_band(val):
  if pd.isna(val):
      return val
  elif val <= 2:
      return '0-2 years'
  elif val <= 5:
      return '2-5 years'
  elif val <= 10:
      return '5-10 years'
  elif val <= 15:
      return '10-15 years'
  else:
      return '15+ years'

# Salary Band
def sal_range(val):
    if pd.isna(val):
        return np.nan
    elif val <= 45000:
        return 'Entry Income'
    elif val <= 75000:
        return 'Mid Income'
    elif val <= 155000:
        return 'Upper Mid Income'
    elif val <= 200000:
        return 'Premium Income'
    else:
        return 'Elite Income'

df["exp_band"]=df['work_exp'].apply(exp_band) # Create work_exp column
df['sal_range']=df['converted_comp_yearly'].apply(sal_range) # Create sal_range column
df['region'] = df['country'].map(region_map).fillna('Other') # Create region column

"""Multi-Select Processing Framework:


Many columns contain multiple answers. Creating a function that would split the values, remove any spaces and count the frequency. As there any columns which have multiple values in the same cell


language_have_worked_with,
language_want_to_work_with,
database_have_worked_with,
database_want_to_work_with,
platform_have_worked_with,
platform_want_to_work_with,
webframe_have_worked_with,
webframe_want_to_work_with,
tools_tech_have_worked_with,
tools_tech_want_to_work_with,
misc_tech_have_worked_with,
misc_tech_want_to_work_with,
dev_type,
learn_code


Using this information we have some primary visualizations such as Top 10 Programming languages used or desired, Top 10 platforms used etc
"""

def multiselect(df, column_name):
    processed = (
        df[column_name]
        .dropna()                 # remove missing values
        .str.split(';')           # split by ;
        .explode()                # convert list items into separate rows
        .str.strip()              # remove extra spaces
        .value_counts()           # count frequency
        .reset_index()
    )

    processed.columns = [column_name, 'count']
    return processed

language_want_counts = multiselect(df, 'language_want_to_work_with')
language_want_counts.head(10) #These functions help in seperating multiple values in the same column and also provide count

devtype_counts = multiselect(df, 'dev_type')
devtype_counts.head(10)

database_used_counts = multiselect(df, 'database_have_worked_with')
database_used_counts.head(10)

"""**SECTION D: EXPLORATORY ANALYSIS & INSIGHTS**

Goal is to understand the survey and plot clear Visualizations

SECTION-A:

In this section we want to identify who are the respondents what is the age distribution, education level, employment status etc
"""

#1. Top Countries by Respondent Count
top_country=df['country'].value_counts().head(10)

top_country=top_country.sort_values()

plt.barh(top_country.index,top_country.values)
plt.xlabel('Country')
plt.ylabel('Count')
plt.title('Top Countries by Respondent Count')
plt.savefig('plots/top_countries_responce.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observations: The united states of America contributes the largest share of the survey responses by a wide margin, followed by Germany and then India.
Which suggests strong participation or large active developer communities in these countries"""

#2.Age Group Distribution
age_group = df['age'].value_counts()

age_pct = (age_group / age_group.sum()) * 100

plt.figure(figsize=(10,6))
plt.barh(age_pct.index[::-1], age_pct.values[::-1])

plt.xlabel('Percentage (%)')
plt.ylabel('Age Group')
plt.title('Age Group Distribution')
plt.savefig('plots/age_grp_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""The largest share of respondents falls within the 25–34 age group, followed by 35–44 years.
This indicates that the survey population is primarily composed of early-to-mid career professionals"""

#3. Education Level Breakdown


education = df['ed_level'].replace({
    r".*Bachelor.*": "Bachelor's degree",
    r".*Master.*": "Master's degree",
    r".*Some college.*": "Some college",
    r".*Secondary school.*": "Secondary school",
    r".*Professional degree.*": "Professional degree",
    r".*Associate degree.*": "Associate degree",
    r".*Primary.*": "Primary school",
    r".*Something else.*": "Other"
}, regex=True)

education = education.value_counts()

education_pct = (education / education.sum()) * 100

plt.figure(figsize=(10,6))
plt.barh(education_pct.index[::-1], education_pct.values[::-1])

plt.xlabel('Percentage (%)')
plt.ylabel('Education Level')
plt.title('3. Education Level Breakdown')

plt.tight_layout()
plt.savefig('plots/edu_level_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Bachelor’s degree holders represent the largest share of respondents, accounting for roughly 40% of the sample, followed by respondents with a Master’s degree.
This suggests that formal higher education remains a common pathway into software and technology careers among survey participants."""

#4. Employment Status

employment = multiselect(df, 'employment')

employment_pct = (employment['count'] / employment['count'].sum()) * 100

plt.figure(figsize=(10,6))
plt.barh(
    employment['employment'][::-1],
    employment_pct[::-1]
)

plt.xlabel('Percentage (%)')
plt.ylabel('Employment Type')
plt.title('4. Employment Status')

plt.tight_layout()
plt.savefig('plots/employment_status_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observation:
Full-time employment represents the largest respondent category, accounting for nearly 60% of all reported employment statuses.
This indicates that the survey is heavily represented by active working professionals.
"""

#5. Main Branch Distribution

main_branch = df['main_branch'].value_counts()

main_branch_pct = (main_branch / main_branch.sum()) * 100

plt.figure(figsize=(10,6))
plt.barh(main_branch_pct.index[::-1], main_branch_pct.values[::-1])

plt.xlabel('Percentage (%)')
plt.ylabel('Main Branch')
plt.title('5. Main Branch Distribution')

plt.tight_layout()
plt.savefig('plots/main_branch_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observation:
The largest share of respondents nearly 80% identify as developers by profession, indicating that coding is a regular part of their primary job responsibilities.
This suggests the survey is strongly centered around professional developers"""

#6. Top Developer Roles

dev_roles = multiselect(df, 'dev_type')

top_roles = dev_roles.head(10)

role_pct = (top_roles['count'] / dev_roles['count'].sum()) * 100

plt.figure(figsize=(10,6))
plt.barh(
    top_roles['dev_type'][::-1],
    role_pct[::-1]
)

plt.xlabel('Percentage (%)')
plt.ylabel('Developer Role')
plt.title('6. Top Developer Roles')

plt.tight_layout()
plt.savefig('plots/top_dev_roles_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observation:
Full-stack developer roles represent the largest share of respondents by a clear margin, followed by back-end and front-end developers.
This suggests that versatile web development roles remain highly prevalent in the industry, while specialized front-end and back-end roles also continue to play major positions in the developer workforce."""

# Dashboard Version: Developer Demographics and Profile Overview

# -----------------------------
# label cleanups
# -----------------------------
main_branch_labels = {
    'I am a developer by profession': 'Professional developer',
    'I am not primarily a developer, but I write code sometimes as part of my work/studies': 'Code as part of work/study',
    'I am learning to code': 'Learning to code',
    'I code primarily as a hobby': 'Hobbyist coder',
    'I used to be a developer by profession, but no longer am': 'Former developer',
    'None of these': 'Other'
}

dev_role_labels = {
    'Developer, full-stack': 'Full-stack developer',
    'Developer, back-end': 'Back-end developer',
    'Developer, front-end': 'Front-end developer',
    'Developer, desktop or enterprise applications': 'Desktop / enterprise developer',
    'Other (please specify):': 'Other',
    'Developer, mobile': 'Mobile developer',
    'Engineering manager': 'Engineering manager',
    'Student': 'Student',
    'Developer, embedded applications or devices': 'Embedded developer',
    'Data scientist or machine learning specialist': 'Data scientist / ML'
}

# -----------------------------
# Cleaned series for dashboard
# -----------------------------
main_branch_clean = main_branch_pct.rename(index=main_branch_labels)

top_roles_clean = top_roles.copy()
top_roles_clean['dev_type'] = top_roles_clean['dev_type'].replace(dev_role_labels)

# -----------------------------
# Helper function for labels
# -----------------------------
def add_bar_labels(ax, values):
    for i, v in enumerate(values):
        ax.text(v + 0.5, i, f'{v:.1f}%', va='center', fontsize=9)

# -----------------------------
# Plot dashboard
# -----------------------------
fig, axes = plt.subplots(2, 3, figsize=(18, 11))

# 1. Age Group Distribution
age_vals = age_pct.values[::-1]
axes[0,0].barh(age_pct.index[::-1], age_vals)
axes[0,0].set_title('1. Age Group Distribution', fontsize=12, pad=10)
axes[0,0].set_xlabel('Percentage (%)')
axes[0,0].set_ylabel('Age Group')
add_bar_labels(axes[0,0], age_vals)

# 2. Education Level Breakdown
edu_vals = education_pct.values[::-1]
axes[0,1].barh(education_pct.index[::-1], edu_vals)
axes[0,1].set_title('2. Education Level Breakdown', fontsize=12, pad=10)
axes[0,1].set_xlabel('Percentage (%)')
axes[0,1].set_ylabel('Education Level')
add_bar_labels(axes[0,1], edu_vals)

# 3. Employment Status
employment_display = employment.head(8).copy()
employment_display['employment'] = employment_display['employment'].replace({
    'Independent contractor, freelancer, or self-employed': 'Freelancer / self-employed',
    'Student, full-time': 'Student (full-time)',
    'Student, part-time': 'Student (part-time)',
    'Not employed, but looking for work': 'Unemployed, seeking work',
    'Not employed, and not looking for work': 'Unemployed, not seeking',
    'I prefer not to say': 'Prefer not to say'
})
employment_display_pct = (employment_display['count'] / employment['count'].sum()) * 100
emp_vals = employment_display_pct.values[::-1]
axes[0,2].barh(employment_display['employment'][::-1], emp_vals)
axes[0,2].set_title('3. Employment Status', fontsize=12, pad=10)
axes[0,2].set_xlabel('Percentage (%)')
axes[0,2].set_ylabel('Employment Type')
add_bar_labels(axes[0,2], emp_vals)

# 4. Main Branch Distribution
main_vals = main_branch_clean.values[::-1]
axes[1,0].barh(main_branch_clean.index[::-1], main_vals)
axes[1,0].set_title('4. Main Branch Distribution', fontsize=12, pad=10)
axes[1,0].set_xlabel('Percentage (%)')
axes[1,0].set_ylabel('Main Branch')
add_bar_labels(axes[1,0], main_vals)

# 5. Top Developer Roles
role_display = top_roles_clean.copy()
role_display_pct = (role_display['count'] / dev_roles['count'].sum()) * 100
role_vals = role_display_pct.values[::-1]
axes[1,1].barh(role_display['dev_type'][::-1], role_vals)
axes[1,1].set_title('5. Top Developer Roles', fontsize=12, pad=10)
axes[1,1].set_xlabel('Percentage (%)')
axes[1,1].set_ylabel('Developer Role')
add_bar_labels(axes[1,1], role_vals)

# 6. Insights Panel
axes[1,2].axis('off')
axes[1,2].text(
    0, 1,
    "Key Insights\n\n"
    "• Most respondents are between 25–34 years old.\n"
    "• Bachelor's and Master's degrees dominate the sample.\n"
    "• Full-time employment is the most common status.\n"
    "• Most respondents identify as professional developers.\n"
    "• Full-stack and back-end roles are the most common.",
    fontsize=11,
    va='top'
)

# -----------------------------
# Final styling
# -----------------------------
plt.suptitle('Developer Demographics and Profile Overview', fontsize=18, y=0.98)
plt.subplots_adjust(wspace=0.75, hspace=0.45)
plt.savefig('plots/developer_demographics_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()

"""**Section 2 — Learning Pathways & Experience**


In this section we want to learn how developers enter and grow in tech.


"""

# Step 1: use your predefined function
learn_df = multiselect(df, 'learn_code')

# Step 2: bin categories
def bin_learn_code(val):
    if pd.isna(val):
        return val
    elif 'Books / Physical media' in val:
        return 'Books'
    elif ('Colleague' in val) or ('On the job training' in val):
        return 'Colleagues / Workplace'
    elif 'Friend or family member' in val:
        return 'Friends / Family'
    elif 'Hackathons' in val:
        return 'Hackathons'
    elif 'Online Courses or Certification' in val:
        return 'Online Courses / Certifications'
    elif 'Other online resources' in val:
        return 'Online Resources'
    elif 'School' in val:
        return 'School / University'
    elif 'Coding Bootcamp' in val:
        return 'Bootcamp'
    else:
        return 'Other'

# Step 3: create grouped category column
learn_df['category'] = learn_df['learn_code'].apply(bin_learn_code)

# Step 4: aggregate counts by category
final_learn = (
    learn_df
    .groupby('category')['count']
    .sum()
    .sort_values()
)

# Step 5: plot
plt.figure(figsize=(10,6))
plt.barh(final_learn.index, final_learn.values)

plt.title('How Developers Learn to Code')
plt.xlabel('Number of Mentions')
plt.ylabel('Learning Source')

plt.tight_layout()
plt.savefig('plots/dev_learn_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observation:
Online resources are the most frequently cited way developers learn to code, followed by learning through colleagues or the workplace.
Traditional sources such as books and formal education also remain highly significant.
."""

"""" Professional Coding experience"""

df['years_code'] = pd.to_numeric(df['years_code'], errors='coerce')
df['years_code_pro'] = pd.to_numeric(df['years_code_pro'], errors='coerce')    #Converting type object to numeric

mean_val = df['years_code_pro'].mean()
median_val = df['years_code_pro'].median()

plt.figure(figsize=(10,6))

plt.hist(df['years_code_pro'].dropna(), bins=20, edgecolor='black')

plt.axvline(mean_val, linestyle='--', label=f'Mean: {mean_val:.1f}')
plt.axvline(median_val, linestyle='-', label=f'Median: {median_val:.1f}')

plt.title('Distribution of Professional Coding Experience')
plt.xlabel('Years of Professional Coding')
plt.ylabel('Number of Respondents')
plt.legend()

plt.tight_layout()
plt.savefig('plots/pro_exp_dist.png', dpi=300, bbox_inches='tight')
plt.show()

""" Observation:
The distribution of professional coding experience is right skewed, with the highest concentration of respondents in the early career range.
Most respondents report fewer than 15 years of professional coding experience. The mean experience (11.3 years) is higher than the median (9 years), indicating the presence of a smaller group of highly experienced professionals.
"""

""" Professional Experience by Education Level"""

# recreate cleaned education column
df['education_clean'] = df['ed_level'].replace({
    r'.*Primary.*': 'Primary school',
    r'.*Secondary school.*': 'Secondary school',
    r'.*Some college.*': 'Some college',
    r'.*Associate degree.*': 'Associate degree',
    r'.*Bachelor.*': "Bachelor's degree",
    r'.*Master.*': "Master's degree",
    r'.*Professional degree.*': 'Professional degree',
    r'.*Something else.*': 'Other'
}, regex=True)


order = [
    'Primary school',
    'Secondary school',
    'Some college',
    'Associate degree',
    "Bachelor's degree",
    "Master's degree",
    'Professional degree',
    'Other'
]

plot_df = df[['education_clean', 'years_code_pro']].dropna()
plot_df['education_clean'] = pd.Categorical(
    plot_df['education_clean'],
    categories=order,
    ordered=True
)

plot_df.boxplot(
    column='years_code_pro',
    by='education_clean',
    figsize=(12,6),
    grid=False,
    rot=0,
    showfliers=False
)

plt.title('Professional Experience by Education Level')
plt.suptitle('')
plt.xlabel('')
plt.ylabel('Years of Professional Experience')
plt.tight_layout()
plt.savefig('plots/pro_exp_edu_dist.png', dpi=300, bbox_inches='tight')
plt.show()


"""" Observation:
Professional coding experience varies across education levels, but the distributions overlap substantially. Respondents with professional degrees and Master’s degrees show higher median experience levels, while lower education categories generally display lower medians.
This suggests that higher educational attainment may be associated with greater professional experience, potentially reflecting longer career progression, specialization, or roles that require advanced qualifications. However, experience is not determined by education alone.
"""

"""Distribution by Experience"""

exp_dist = df['exp_band'].value_counts()

order = ['0-2 years', '2-5 years', '5-10 years', '10-15 years', '15+ years']

exp_dist = df['exp_band'].value_counts().reindex(order)

plt.figure(figsize=(10,6))

plt.barh(exp_dist.index, exp_dist.values)

plt.title('Developer Distribution by Experience Band')
plt.xlabel('Number of Respondents')
plt.ylabel('Experience Band')

plt.tight_layout()
plt.show()

plot_df = df[['education_clean', 'years_code_pro']].dropna()
plot_df = plot_df[plot_df['years_code_pro'] <= 50]
plt.savefig('plots/dev_exp_dist.png', dpi=300, bbox_inches='tight')

"""Observation:
Respondents are concentrated in the mid-to-senior experience ranges, with the highest counts in the 5–10 years and 15+ years bands.
Early-career developers (0–2 years) represent the smallest group in this distribution. """

# -----------------------------
# DASHBOARD
# -----------------------------
fig = plt.figure(figsize=(24, 12))
gs = fig.add_gridspec(2, 3, width_ratios=[1.1, 1.1, 0.9], hspace=0.35, wspace=0.3)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])
ax_text = fig.add_subplot(gs[:, 2])

fig.suptitle('Stack Overflow Developer Survey 2023 Dashboard', fontsize=20, fontweight='bold', y=0.98)

# -----------------------------
# Plot 1: Experience Band Distribution
# -----------------------------
ax1.barh(exp_dist.index, exp_dist.values)
ax1.set_title('Developer Distribution by Experience Band', fontsize=13, fontweight='bold')
ax1.set_xlabel('Number of Respondents')
ax1.set_ylabel('Experience Band')
ax1.grid(axis='x', linestyle='--', alpha=0.4)

for i, v in enumerate(exp_dist.values):
    if pd.notna(v):
        ax1.text(v + max(exp_dist.values)*0.01, i, str(int(v)), va='center', fontsize=9)

# -----------------------------
# Plot 2: Professional Coding Experience
# -----------------------------
mean_pro = df['years_code_pro'].mean()
median_pro = df['years_code_pro'].median()


ax2.hist(df['years_code_pro'].dropna(), bins=20, edgecolor='black')
ax2.axvline(mean_pro, linestyle='--', linewidth=2, label=f'Mean: {mean_pro:.1f}')
ax2.axvline(median_pro, linestyle='-', linewidth=2, label=f'Median: {median_pro:.1f}')
ax2.set_title('Distribution of Professional Coding Experience', fontsize=13, fontweight='bold')
ax2.set_xlabel('Years of Professional Coding')
ax2.set_ylabel('Number of Respondents')
ax2.grid(axis='y', linestyle='--', alpha=0.4)
ax2.legend()

# -----------------------------
# Plot 3: Education vs Experience
# -----------------------------
plot_df.boxplot(
    column='years_code_pro',
    by='education_clean',
    ax=ax3,
    grid=False,
    rot=20,
    showfliers=False
)
ax3.set_title('Professional Experience by Education Level', fontsize=13, fontweight='bold')
ax3.set_xlabel('Education Level')
ax3.set_ylabel('Years of Professional Experience')

# remove pandas automatic subtitle
fig.suptitle('Stack Overflow Developer Survey 2023 Dashboard', fontsize=20, fontweight='bold', y=0.98)

# -----------------------------
# Plot 4: Learning Sources
# -----------------------------
ax4.barh(final_learn.index, final_learn.values)
ax4.set_title('How Developers Learn to Code', fontsize=13, fontweight='bold')
ax4.set_xlabel('Number of Mentions')
ax4.set_ylabel('Learning Source')
ax4.grid(axis='x', linestyle='--', alpha=0.4)

for i, v in enumerate(final_learn.values):
    ax4.text(v + max(final_learn.values)*0.01, i, str(int(v)), va='center', fontsize=9)

# -----------------------------
# Insights Panel
# -----------------------------
ax_text.axis('off')

insight_text = """
Dashboard Insights

1. Experience distribution
Most respondents fall within the
0–10 years range, indicating that
the survey population is dominated
by early and mid career developers.

2. Professional coding experience
The histogram is right-skewed, which
shows a larger share of respondents
in the earlier professional stages
and a smaller veteran segment.

3. Education vs experience
Higher education categories tend to
show somewhat higher median
experience, but there is strong
overlap across all groups.

4. Learning pathways
Developers rely heavily on online
resources, formal education, and
workplace learning, showing that
developer growth is multi channel
rather than dependent on a single path.

Overall takeaway
The survey reflects a globally broad,
career diverse developer community
with strong early/mid-career
representation and varied learning
backgrounds.
"""

ax_text.text(
    0, 1, insight_text,
    va='top',
    fontsize=12,
    linespacing=1.5,
    bbox=dict(boxstyle='round,pad=0.6', facecolor='whitesmoke', edgecolor='gray')
)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('plots/developer_experience_learning_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()

"""**SECTION 3 — Technology Landscape**

In this section we want to learn what the current vs future technology trends are what are the top languages, databases, platforms, frameworks used in the industry.
"""

"""A.Programming Languages"""

# Step 1: Process multiselect column
language_counts = multiselect(df, 'language_have_worked_with')

# Step 2: Get Top 10 and sort for horizontal bar chart
top_lang = language_counts.head(10).sort_values(by='count')

# Step 3: Plot
plt.figure(figsize=(10,6))

plt.barh(top_lang['language_have_worked_with'], top_lang['count'])

plt.title('Top 10 Programming Languages Used')
plt.xlabel('Number of Developers')
plt.ylabel('Programming Language')

plt.tight_layout()
plt.savefig('plots/top_lang_dist.png', dpi=300, bbox_inches='tight')
plt.show()

"""Observation:
JavaScript is the most widely used programming language among respondents, followed by HTML/CSS, Python, and SQL. The rankings highlight a strong concentration around web development and data-related technologies.
This suggests that web technologies continue to dominate the developer ecosystem, while Python and SQL remain highly valuable due to their broad use in automation, analytics, backend systems, and data driven applications.
"""

"""B.Programming Languages Desired"""

# Step 1: Process desired languages column
language_want_counts = multiselect(df, 'language_want_to_work_with')

# Step 2: Select top 10 and sort for horizontal chart
top_want = language_want_counts.head(10).sort_values(by='count')

# Step 3: Plot
plt.figure(figsize=(10,6))

plt.barh(
    top_want['language_want_to_work_with'],
    top_want['count']
)

plt.title('Top 10 Programming Languages Desired')
plt.xlabel('Number of Developers')
plt.ylabel('Programming Language')

plt.tight_layout()
plt.savefig('plots/top_lang_desired.png', dpi=300, bbox_inches='tight')
plt.show()

"""
C. Used vs Desired Languages
"""

# Step 1: Process both columns
used_lang = multiselect(df, 'language_have_worked_with')
want_lang = multiselect(df, 'language_want_to_work_with')

# Step 2: Rename columns for merge
used_lang.columns = ['language', 'used_count']
want_lang.columns = ['language', 'desired_count']

# Step 3: Merge
lang_compare = pd.merge(
    used_lang,
    want_lang,
    on='language',
    how='outer'
).fillna(0)

# Step 4: Total popularity score
lang_compare['total'] = (
    lang_compare['used_count'] +
    lang_compare['desired_count']
)

# Step 5: Keep top 10 by total interest
top_compare = (
    lang_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

# -----------------------------------
# Plot
# -----------------------------------
plt.figure(figsize=(12,7))

bar_width = 0.4
y = range(len(top_compare))

plt.barh(
    [i - bar_width/2 for i in y],
    top_compare['used_count'],
    height=bar_width,
    label='Used'
)

plt.barh(
    [i + bar_width/2 for i in y],
    top_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

plt.yticks(y, top_compare['language'])

plt.title('Used vs Desired Programming Languages')
plt.xlabel('Number of Developers')
plt.ylabel('Programming Language')
plt.legend()

plt.tight_layout()
plt.savefig('plots/used_vs_desired.png', dpi=300, bbox_inches='tight')
plt.show()

""" Observation:
JavaScript, HTML/CSS, Python, and SQL remain highly used languages, but several languages show stronger future interest relative to their current usage. Rust stands out with desired usage significantly exceeding current usage, while TypeScript and Python also maintain strong demand.
This suggests that established languages continue to dominate day-to-day development, while newer or high-performance languages such as Rust are attracting growing interest. The gap between current and desired usage can indicate learning intentions, career transitions, or emerging technology trends.
"""

"""
# D. Desire Gap Ranking
"""

# Step 1: Process both columns
used_lang = multiselect(df, 'language_have_worked_with')
want_lang = multiselect(df, 'language_want_to_work_with')

# Step 2: Rename columns
used_lang.columns = ['language', 'used_count']
want_lang.columns = ['language', 'desired_count']

# Step 3: Merge both datasets
gap_df = pd.merge(
    used_lang,
    want_lang,
    on='language',
    how='outer'
).fillna(0)

# Step 4: Create desire gap
gap_df['desire_gap'] = (
    gap_df['desired_count'] -
    gap_df['used_count']
)

# Step 5: Top positive gap languages
top_gap = (
    gap_df
    .sort_values(by='desire_gap', ascending=False)
    .head(10)
    .sort_values(by='desire_gap')
)

# -----------------------------------
# Plot
# -----------------------------------
plt.figure(figsize=(10,6))

plt.barh(
    top_gap['language'],
    top_gap['desire_gap']
)

plt.title('Top Languages with Highest Desire Gap')
plt.xlabel('Desired Count - Used Count')
plt.ylabel('Programming Language')

plt.tight_layout()
plt.savefig('plots/lang_with_highest_desired_gap.png', dpi=300, bbox_inches='tight')
plt.show()

""" Observation:
Rust shows the largest positive desire gap among programming languages, meaning interest in learning or working with Rust significantly exceeds its current usage. Go ranks second, followed by Zig, Kotlin, and Elixir.
This suggests that developers are actively exploring languages associated with performance, modern systems programming, scalability, and reliability. The desire gap can highlight where future adoption or skill building interest may grow faster than current usage levels.
"""

# PREP DATA

# 1. Top Languages Used
used_lang = multiselect(df, 'language_have_worked_with')
top_used = used_lang.head(10).sort_values(by='count')

# 2. Top Languages Desired
want_lang = multiselect(df, 'language_want_to_work_with')
top_want = want_lang.head(10).sort_values(by='count')

# 3. Used vs Desired Languages
used_compare = multiselect(df, 'language_have_worked_with')
want_compare = multiselect(df, 'language_want_to_work_with')

used_compare.columns = ['language', 'used_count']
want_compare.columns = ['language', 'desired_count']

lang_compare = pd.merge(
    used_compare,
    want_compare,
    on='language',
    how='outer'
).fillna(0)

lang_compare['total'] = lang_compare['used_count'] + lang_compare['desired_count']

top_compare = (
    lang_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

# 4. Desire Gap Ranking
gap_df = lang_compare.copy()
gap_df['desire_gap'] = gap_df['desired_count'] - gap_df['used_count']

top_gap = (
    gap_df
    .sort_values(by='desire_gap', ascending=False)
    .head(10)
    .sort_values(by='desire_gap')
)

# -----------------------------------
# DASHBOARD
# -----------------------------------
fig = plt.figure(figsize=(24, 12))
gs = fig.add_gridspec(2, 3, width_ratios=[1.1, 1.1, 0.9], hspace=0.35, wspace=0.3)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])
ax_text = fig.add_subplot(gs[:, 2])

fig.suptitle('Programming Languages Dashboard', fontsize=20, fontweight='bold', y=0.98)

# -----------------------------------
# Plot 1: Top Languages Used
# -----------------------------------
ax1.barh(top_used['language_have_worked_with'], top_used['count'])
ax1.set_title('Top 10 Programming Languages Used', fontsize=13, fontweight='bold')
ax1.set_xlabel('Number of Developers')
ax1.set_ylabel('Programming Language')
ax1.grid(axis='x', linestyle='--', alpha=0.4)

for i, v in enumerate(top_used['count']):
    ax1.text(v + max(top_used['count']) * 0.01, i, str(int(v)), va='center', fontsize=9)

# -----------------------------------
# Plot 2: Top Languages Desired
# -----------------------------------
ax2.barh(top_want['language_want_to_work_with'], top_want['count'])
ax2.set_title('Top 10 Programming Languages Desired', fontsize=13, fontweight='bold')
ax2.set_xlabel('Number of Developers')
ax2.set_ylabel('Programming Language')
ax2.grid(axis='x', linestyle='--', alpha=0.4)

for i, v in enumerate(top_want['count']):
    ax2.text(v + max(top_want['count']) * 0.01, i, str(int(v)), va='center', fontsize=9)

# -----------------------------------
# Plot 3: Used vs Desired Languages
# -----------------------------------
bar_width = 0.4
y = np.arange(len(top_compare))

ax3.barh(
    y - bar_width/2,
    top_compare['used_count'],
    height=bar_width,
    label='Used'
)

ax3.barh(
    y + bar_width/2,
    top_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

ax3.set_yticks(y)
ax3.set_yticklabels(top_compare['language'])
ax3.set_title('Used vs Desired Programming Languages', fontsize=13, fontweight='bold')
ax3.set_xlabel('Number of Developers')
ax3.set_ylabel('Programming Language')
ax3.legend()
ax3.grid(axis='x', linestyle='--', alpha=0.4)

# -----------------------------------
# Plot 4: Desire Gap Ranking
# -----------------------------------
ax4.barh(top_gap['language'], top_gap['desire_gap'])
ax4.set_title('Top Languages with Highest Desire Gap', fontsize=13, fontweight='bold')
ax4.set_xlabel('Desired Count - Used Count')
ax4.set_ylabel('Programming Language')
ax4.grid(axis='x', linestyle='--', alpha=0.4)

for i, v in enumerate(top_gap['desire_gap']):
    ax4.text(v + max(top_gap['desire_gap']) * 0.01, i, str(int(v)), va='center', fontsize=9)

# -----------------------------------
# Insights Panel
# -----------------------------------
ax_text.axis('off')

insight_text=""" Dashboard Insights

1. Top languages used
A small group of languages such
as JavaScript HTML/CSS and python
dominates current usage, showing strong
industry standardization around
widely adopted tools.

2. Top languages desired
Rust is the most desired languages
reflect current relevance,
but also reveal where
developer interest is shifting.

3. Used vs desired comparison
Some languages remain strong in both
current use and future preference.

4. Desire gap
Languages with the highest positive
desire gap indicate rising interest
and future growth potential rather
than just present adoption.

Overall takeaway
The language ecosystem contains both
stable mainstream technologies and
high interest emerging languages.
This comparison helps distinguish
what is popular now from what may
become more important next. """

ax_text.text(
    0, 1, insight_text,
    va='top',
    fontsize=12,
    linespacing=1.5,
    bbox=dict(boxstyle='round,pad=0.6', facecolor='whitesmoke', edgecolor='gray')
)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('plots/programming_lang_used_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()

"""B Top databases Used"""

database_used = multiselect(df, 'database_have_worked_with')
top_db_used = database_used.head(10).sort_values(by='count')

plt.figure(figsize=(10, 6))
plt.barh(top_db_used['database_have_worked_with'], top_db_used['count'])

plt.title('Top 10 Databases Used')
plt.xlabel('Number of Developers')
plt.ylabel('Database')

plt.tight_layout()
plt.savefig('plots/top_databases', dpi=300, bbox_inches='tight')
plt.show()

"""Used vs Desired Databases"""


db_used = multiselect(df, 'database_have_worked_with')
db_want = multiselect(df, 'database_want_to_work_with')

db_used.columns = ['database', 'used_count']
db_want.columns = ['database', 'desired_count']

db_compare = pd.merge(
    db_used,
    db_want,
    on='database',
    how='outer'
).fillna(0)

db_compare['total'] = db_compare['used_count'] + db_compare['desired_count']

top_db_compare = (
    db_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

plt.figure(figsize=(12, 7))

bar_width = 0.4
y = np.arange(len(top_db_compare))

plt.barh(
    y - bar_width/2,
    top_db_compare['used_count'],
    height=bar_width,
    label='Used'
)

plt.barh(
    y + bar_width/2,
    top_db_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

plt.yticks(y, top_db_compare['database'])

plt.title('Used vs Desired Databases')
plt.xlabel('Number of Developers')
plt.ylabel('Database')
plt.legend()

plt.tight_layout()
plt.savefig('plots/databases_used_vs_desired.png', dpi=300, bbox_inches='tight')
plt.show()


"""
Observation:
PostgreSQL is the most widely used and desired database among respondents, followed by MySQL and SQLite. Most databases show higher current usage than future desire, while Redis stands out with relatively strong desired interest close to its current usage.
This suggests that established databases continue to dominate real world developer workflows, with PostgreSQL showing especially strong momentum. At the same time, technologies like Redis remain attractive.

"""

""" C. Platforms/ Cloud """
platform_used = multiselect(df, 'platform_have_worked_with')
top_platform_used = platform_used.head(10).sort_values(by='count')

plt.figure(figsize=(10, 6))
plt.barh(
    top_platform_used['platform_have_worked_with'],
    top_platform_used['count']
)

plt.title('Top 10 Platforms Used')
plt.xlabel('Number of Developers')
plt.ylabel('Platform')

plt.tight_layout()
plt.savefig('plots/top_platform_used.png', dpi=300, bbox_inches='tight')
plt.show()

#D. Used vs Desired Platforms

plat_used = multiselect(df, 'platform_have_worked_with')
plat_want = multiselect(df, 'platform_want_to_work_with')

plat_used.columns = ['platform', 'used_count']
plat_want.columns = ['platform', 'desired_count']

plat_compare = pd.merge(
    plat_used,
    plat_want,
    on='platform',
    how='outer'
).fillna(0)

plat_compare['total'] = (
    plat_compare['used_count'] +
    plat_compare['desired_count']
)

top_plat_compare = (
    plat_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

plt.figure(figsize=(12, 7))

bar_width = 0.4
y = np.arange(len(top_plat_compare))

plt.barh(
    y - bar_width/2,
    top_plat_compare['used_count'],
    height=bar_width,
    label='Used'
)

plt.barh(
    y + bar_width/2,
    top_plat_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

plt.yticks(y, top_plat_compare['platform'])

plt.title('Used vs Desired Platforms')
plt.xlabel('Number of Developers')
plt.ylabel('Platform')
plt.legend()

plt.tight_layout()
plt.savefig('plots/platforms_used_vs_desired.png', dpi=300, bbox_inches='tight')
plt.show()

""" Observation:
Amazon Web Services (AWS) is the most widely used and desired platform among respondents, followed by Microsoft Azure and Google Cloud. Across most platforms, current usage exceeds future desire, though major cloud providers continue to maintain strong interest.
This suggests that cloud computing remains central to modern development workflows, with AWS holding a leading position in adoption and mindshare. Azure and Google Cloud also show strong relevance, reflecting a competitive multi cloud ecosystem.
"""

""" D. Framework/ Tools"""
framework_used = multiselect(df, 'webframe_have_worked_with')
top_framework = framework_used.head(10).sort_values(by='count')

plt.figure(figsize=(10, 6))
plt.barh(
    top_framework['webframe_have_worked_with'],
    top_framework['count']
)

plt.title('Top 10 Web Frameworks Used')
plt.xlabel('Number of Developers')
plt.ylabel('Web Framework')

plt.savefig('plots/top_webframes.png', dpi=300, bbox_inches='tight')

plt.tight_layout()
plt.show()

"""
E. Web Frameworks: Used vs Desired
"""

wf_used = multiselect(df, 'webframe_have_worked_with')
wf_want = multiselect(df, 'webframe_want_to_work_with')

wf_used.columns = ['framework', 'used_count']
wf_want.columns = ['framework', 'desired_count']

wf_compare = pd.merge(
    wf_used,
    wf_want,
    on='framework',
    how='outer'
).fillna(0)

wf_compare['total'] = (
    wf_compare['used_count'] +
    wf_compare['desired_count']
)

top_wf_compare = (
    wf_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

plt.figure(figsize=(12,7))

bar_width = 0.4
y = np.arange(len(top_wf_compare))

plt.barh(
    y - bar_width/2,
    top_wf_compare['used_count'],
    height=bar_width,
    label='Used'
)

plt.barh(
    y + bar_width/2,
    top_wf_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

plt.yticks(y, top_wf_compare['framework'])

plt.title('Used vs Desired Web Frameworks')
plt.xlabel('Number of Developers')
plt.ylabel('Framework')
plt.legend()

plt.tight_layout()
plt.savefig('plots/top_webframes_used_vs_desired.png', dpi=300, bbox_inches='tight')
plt.show()

""" Observation:
Node.js and React are the most widely used and desired web technologies among respondents, indicating continued dominance in modern web development. Most established frameworks show higher current usage than future desire, while Next.js stands out with desired usage exceeding its current adoption.
This suggests that mature ecosystems such as React and Node.js remain foundational tools for developers, while newer frameworks like Next.js are gaining momentum due to demand for performance, server-side rendering, and full stack web capabilities.
"""

"""
#F Developer Tools Usage
"""

tool_used = multiselect(df, 'tools_tech_have_worked_with')
top_tools = tool_used.head(10).sort_values(by='count')

plt.figure(figsize=(10, 6))
plt.barh(
    top_tools['tools_tech_have_worked_with'],
    top_tools['count']
)

plt.title('Top 10 Developer Tools Used')
plt.xlabel('Number of Developers')
plt.ylabel('Tool')
plt.savefig('plots/top_dev_tools.png', dpi=300, bbox_inches='tight')

plt.tight_layout()
plt.show()

"""
G. Developer Tools: Used vs Desired
"""

tool_used = multiselect(df, 'tools_tech_have_worked_with')
tool_want = multiselect(df, 'tools_tech_want_to_work_with')

tool_used.columns = ['tool', 'used_count']
tool_want.columns = ['tool', 'desired_count']

tool_compare = pd.merge(
    tool_used,
    tool_want,
    on='tool',
    how='outer'
).fillna(0)

tool_compare['total'] = (
    tool_compare['used_count'] +
    tool_compare['desired_count']
)

top_tool_compare = (
    tool_compare
    .sort_values(by='total', ascending=False)
    .head(10)
    .sort_values(by='used_count')
)

plt.figure(figsize=(12,7))

bar_width = 0.4
y = np.arange(len(top_tool_compare))

plt.barh(
    y - bar_width/2,
    top_tool_compare['used_count'],
    height=bar_width,
    label='Used'
)

plt.barh(
    y + bar_width/2,
    top_tool_compare['desired_count'],
    height=bar_width,
    label='Desired'
)

plt.yticks(y, top_tool_compare['tool'])

plt.title('Used vs Desired Developer Tools')
plt.xlabel('Number of Developers')
plt.ylabel('Tool')
plt.legend()

plt.tight_layout()
plt.savefig('plots/ptop_dev_tools_used_vs_desired.png', dpi=300, bbox_inches='tight')
plt.show()

"""
Observation:
Docker is the most widely used and desired developer tool among respondents, followed by npm and Pip. While many established tools show higher current usage than future desire, Kubernetes, Vite, and Cargo display stronger desired interest relative to their current usage.

Interpretation:
This suggests that containerization and package management remain core parts of modern development workflows. At the same time, tools related to cloud- ative infrastructure, modern frontend build systems, and systems programming ecosystems are gaining momentum among developers.
"""

# =====================================================
# HELPER FUNCTION
# Creates top comparison dataframe for any category
# =====================================================
def compare_multiselect(df, used_col, want_col, label_name):

    used = multiselect(df, used_col)
    want = multiselect(df, want_col)

    used.columns = [label_name, 'used_count']
    want.columns = [label_name, 'desired_count']

    compare = pd.merge(
        used,
        want,
        on=label_name,
        how='outer'
    ).fillna(0)

    compare['total'] = compare['used_count'] + compare['desired_count']

    top_compare = (
        compare
        .sort_values(by='total', ascending=False)
        .head(10)
        .sort_values(by='used_count')
    )

    return top_compare


# =====================================================
# PREP ALL DATA
# =====================================================

# 1. Languages
lang_df = compare_multiselect(
    df,
    'language_have_worked_with',
    'language_want_to_work_with',
    'Technology'
)

# 2. Databases
db_df = compare_multiselect(
    df,
    'database_have_worked_with',
    'database_want_to_work_with',
    'Technology'
)

# 3. Platforms / Cloud
plat_df = compare_multiselect(
    df,
    'platform_have_worked_with',
    'platform_want_to_work_with',
    'Technology'
)

# 4. Web Frameworks
web_df = compare_multiselect(
    df,
    'webframe_have_worked_with',
    'webframe_want_to_work_with',
    'Technology'
)

# 5. Developer Tools
tool_df = compare_multiselect(
    df,
    'tools_tech_have_worked_with',
    'tools_tech_want_to_work_with',
    'Technology'
)

# =====================================================
# DASHBOARD
# =====================================================

fig = plt.figure(figsize=(26, 14))
gs = fig.add_gridspec(3, 2, hspace=0.45, wspace=0.35)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])
ax5 = fig.add_subplot(gs[2, 0])
ax_text = fig.add_subplot(gs[2, 1])

fig.suptitle(
    'Used vs Desired Technologies Dashboard',
    fontsize=22,
    fontweight='bold',
    y=0.98
)

# =====================================================
# PLOT FUNCTION
# =====================================================
def plot_compare(ax, data, title):

    bar_width = 0.4
    y = np.arange(len(data))

    ax.barh(
        y - bar_width/2,
        data['used_count'],
        height=bar_width,
        label='Used'
    )

    ax.barh(
        y + bar_width/2,
        data['desired_count'],
        height=bar_width,
        label='Desired'
    )

    ax.set_yticks(y)
    ax.set_yticklabels(data['Technology'])
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel('Developers')
    ax.grid(axis='x', linestyle='--', alpha=0.4)


# =====================================================
# DRAW CHARTS
# =====================================================

plot_compare(ax1, lang_df, 'Languages: Used vs Desired')
plot_compare(ax2, db_df, 'Databases: Used vs Desired')
plot_compare(ax3, plat_df, 'Platforms / Cloud: Used vs Desired')
plot_compare(ax4, web_df, 'Web Frameworks: Used vs Desired')
plot_compare(ax5, tool_df, 'Developer Tools: Used vs Desired')

ax1.legend()

# =====================================================
# INSIGHTS PANEL
# =====================================================
ax_text.axis('off')

insight_text = """
Dashboard Insights

1. Stable technologies
Items ranking high in both used and
desired counts show strong current
adoption with continued future demand.

2. Growth opportunities
Technologies where desired exceeds
used suggest rising interest and
potential future expansion.

3. Mature ecosystems
Some tools remain heavily used even
if future desire is lower, indicating
established but less aspirational
technologies.

4. Cross-category view
The comparison across languages,
databases, cloud, frameworks, and
tools gives a broader picture of the
modern developer stack.

Overall takeaway
The developer ecosystem includes
both dominant mature technologies
and high-interest emerging tools.
Used vs desired analysis reveals
what matters today and what may
matter more tomorrow.
"""

ax_text.text(
    0,
    1,
    insight_text,
    va='top',
    fontsize=12,
    linespacing=1.5,
    bbox=dict(
        boxstyle='round,pad=0.6',
        facecolor='whitesmoke',
        edgecolor='gray'
    )
)
plt.savefig('plots/used_vs_desired_tech_dashboard.png', dpi=300, bbox_inches='tight')
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

#Select target roles
target_roles = [
    'Developer, full-stack',
    'Developer, back-end',
    'Developer, front-end',
    'Data scientist or machine learning specialist'
]


#Create subset with relevant columns
role_lang_df = df[['dev_type', 'language_have_worked_with']].dropna().copy()


# Explode developer roles
role_lang_df['dev_type'] = role_lang_df['dev_type'].str.split(';')
role_lang_df = role_lang_df.explode('dev_type')
role_lang_df['dev_type'] = role_lang_df['dev_type'].str.strip()

# Keep only selected roles
role_lang_df = role_lang_df[role_lang_df['dev_type'].isin(target_roles)]


# Explode languages
role_lang_df['language_have_worked_with'] = role_lang_df['language_have_worked_with'].str.split(';')
role_lang_df = role_lang_df.explode('language_have_worked_with')
role_lang_df['language_have_worked_with'] = role_lang_df['language_have_worked_with'].str.strip()


# Plot small multiples
fig, axes = plt.subplots(2, 2, figsize=(16, 10))
axes = axes.flatten()

for ax, role in zip(axes, target_roles):
    top_langs = (
        role_lang_df[role_lang_df['dev_type'] == role]
        ['language_have_worked_with']
        .value_counts()
        .head(8)
        .sort_values()
    )

    ax.barh(top_langs.index, top_langs.values)
    ax.set_title(role)
    ax.set_xlabel('Developers')
    ax.set_ylabel('Language')

plt.suptitle('Top Programming Languages by Developer Role', fontsize=18, fontweight='bold', y=1.02)
plt.savefig('plots/top_programming_lang_by_dev_role.png', dpi=300, bbox_inches='tight')
plt.tight_layout()
plt.show()

exp_lang_df = df[['exp_band', 'language_have_worked_with']].dropna().copy()


# Explode languages
exp_lang_df['language_have_worked_with'] = exp_lang_df['language_have_worked_with'].str.split(';')
exp_lang_df = exp_lang_df.explode('language_have_worked_with')
exp_lang_df['language_have_worked_with'] = exp_lang_df['language_have_worked_with'].str.strip()


# Define experience order

exp_order = ['0-2 years', '2-5 years', '5-10 years', '10-15 years', '15+ years']
exp_lang_df['exp_band'] = pd.Categorical(
    exp_lang_df['exp_band'],
    categories=exp_order,
    ordered=True
)

 # Top 10 languages overall

top_languages = (
    exp_lang_df['language_have_worked_with']
    .value_counts()
    .head(10)
    .index
)

filtered_df = exp_lang_df[exp_lang_df['language_have_worked_with'].isin(top_languages)]


 # Create pivot table
heatmap_data = pd.crosstab(
    filtered_df['exp_band'],
    filtered_df['language_have_worked_with']
)

# reorder columns by total popularity
heatmap_data = heatmap_data[top_languages]


# Plot heatmap

heatmap_pct = heatmap_data.div(heatmap_data.sum(axis=1), axis=0) * 100

plt.figure(figsize=(12, 6))
plt.imshow(heatmap_pct, aspect='auto')

plt.title('Technology Usage by Experience Band (%)', fontsize=16, fontweight='bold')
plt.xlabel('Programming Language')
plt.ylabel('Experience Band')

plt.xticks(range(len(heatmap_pct.columns)), heatmap_pct.columns, rotation=45, ha='right')
plt.yticks(range(len(heatmap_pct.index)), heatmap_pct.index)

plt.colorbar(label='Percentage within Experience Band')
plt.tight_layout()
plt.savefig('plots/tech_usage_by_exp.png', dpi=300, bbox_inches='tight')
plt.show()

"""**SECTION 4 — Yearly compensation Analysis**

The goal here is to understand the yearly compensation. What technologies attract the most salary, salary with respect to experience etc.

"""

"""1. Salary Distribution"""

# Convert to numeric if needed
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

# Remove extreme outliers for better readability (optional)
salary_plot = df[df['converted_comp_yearly'] <= 300000]

# Mean / Median
mean_sal = salary_plot['converted_comp_yearly'].mean()
median_sal = salary_plot['converted_comp_yearly'].median()

plt.figure(figsize=(10,6))

plt.hist(
    salary_plot['converted_comp_yearly'].dropna(),
    bins=30,
    edgecolor='black'
)

plt.axvline(mean_sal, linestyle='--', label=f'Mean: {mean_sal:,.0f}')
plt.axvline(median_sal, linestyle='-', label=f'Median: {median_sal:,.0f}')

plt.title('Salary Distribution (Annual Compensation)')
plt.xlabel('Annual Salary (USD)')
plt.ylabel('Number of Respondents')
plt.savefig('plots/annual_sal_dist.png', dpi=300, bbox_inches='tight')
plt.legend()

plt.tight_layout()
plt.show()

"""2. Median Salary Distribution"""
# =====================================
# Median Salary by Salary Range
# Using converted_comp_yearly + sal_range
# =====================================

# Ensure numeric salary
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

# Keep valid rows
salary_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['sal_range'].notna())
].copy()

# Median salary for each salary range
median_sal = (
    salary_df
    .groupby('sal_range')['converted_comp_yearly']
    .median()
    .sort_values()
)

# Plot
plt.figure(figsize=(12,6))

plt.barh(
    median_sal.index,
    median_sal.values
)

plt.title('Median Salary by Salary Range')
plt.xlabel('Median Annual Salary (USD)')
plt.ylabel('Salary Range')

# Value labels
for i, v in enumerate(median_sal.values):
    plt.text(v, i, f' ${v:,.0f}', va='center')

plt.tight_layout()
plt.show()

"""3. Salary by Education Level"""

# =====================================
# Salary by Education Level
# =====================================

# Ensure numeric salary
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

# Recreate cleaned education column if missing
df['education_clean'] = df['ed_level'].replace({
    r".*Bachelor.*": "Bachelor's degree",
    r".*Master.*": "Master's degree",
    r".*Some college.*": "Some college",
    r".*Secondary school.*": "Secondary school",
    r".*Professional degree.*": "Professional degree",
    r".*Associate degree.*": "Associate degree",
    r".*Primary.*": "Primary school",
    r".*Something else.*": "Other"
}, regex=True)

# Keep valid rows
edu_salary = df[
    (df['converted_comp_yearly'] > 0) &
    (df['education_clean'].notna())
].copy()

# Order categories
order = [
    'Primary school',
    'Secondary school',
    'Some college',
    'Associate degree',
    "Bachelor's degree",
    "Master's degree",
    'Professional degree',
    'Other'
]

edu_salary['education_clean'] = pd.Categorical(
    edu_salary['education_clean'],
    categories=order,
    ordered=True
)

# Plot (boxplot is best for salary spread + median)
plt.figure(figsize=(12,6))

edu_salary.boxplot(
    column='converted_comp_yearly',
    by='education_clean',
    grid=False,
    rot=20,
    showfliers=False
)

plt.title('Salary by Education Level')
plt.suptitle('')
plt.xlabel('Education Level')
plt.ylabel('Annual Salary (USD)')
plt.savefig('plots/annual_sal_edu.png', dpi=300, bbox_inches='tight')

plt.tight_layout()
plt.show()

""" 4. Top countries by median salary """


# Top Countries by Median Salary
# (with minimum response threshold)

# Ensure salary numeric
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

# Keep valid rows
country_salary = df[
    (df['converted_comp_yearly'] > 0) &
    (df['country'].notna())
].copy()


# Set minimum respondents needed

min_responses = 100


country_counts = country_salary['country'].value_counts()


valid_countries = country_counts[country_counts >= min_responses].index

filtered_df = country_salary[
    country_salary['country'].isin(valid_countries)
]

# Median salary by country
median_country_salary = (
    filtered_df
    .groupby('country')['converted_comp_yearly']
    .median()
    .sort_values(ascending=False)
    .head(10)
)

# Plot
plt.figure(figsize=(12,7))

plt.barh(
    median_country_salary.index[::-1],
    median_country_salary.values[::-1]
)

plt.title(f'Top Countries by Median Salary (min {min_responses} responses)')
plt.xlabel('Median Annual Salary (USD)')
plt.ylabel('Country')


for i, val in enumerate(median_country_salary.values[::-1]):
    plt.text(val, i, f' ${val:,.0f}', va='center')

plt.tight_layout()
plt.savefig('plots/top_countries_highest_sal.png', dpi=300, bbox_inches='tight')
plt.show()

"""5. Salary by developer Role"""

# Ensure numeric salary
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)


role_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['dev_type'].notna())
].copy()


# Explode multi-select roles

role_df['dev_type'] = role_df['dev_type'].str.split(';')
role_df = role_df.explode('dev_type')
role_df['dev_type'] = role_df['dev_type'].str.strip()


# Minimum threshold

min_responses = 100

role_counts = role_df['dev_type'].value_counts()
valid_roles = role_counts[role_counts >= min_responses].index

role_df = role_df[role_df['dev_type'].isin(valid_roles)]


# Median salary by role

role_salary = (
    role_df
    .groupby('dev_type')['converted_comp_yearly']
    .median()
    .sort_values()
    .tail(12)
)

# Plot

plt.figure(figsize=(12,8))

plt.scatter(
    role_salary.values,
    role_salary.index,
    s=130
)


for y, x in zip(role_salary.index, role_salary.values):
    plt.plot([0, x], [y, y], linewidth=1.5)

for i, val in enumerate(role_salary.values):
    plt.text(val + 2000, i, f'${val:,.0f}', va='center')

plt.title('Median Salary by Developer Role')
plt.xlabel('Median Annual Salary (USD)')
plt.ylabel('Developer Role')

plt.tight_layout()
plt.savefig('plots/sal_dev_role.png', dpi=300, bbox_inches='tight')
plt.show()

"""5. Salary by industry"""

# Ensure numeric salary
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

# Keep valid rows
industry_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['industry'].notna())
].copy()

# Minimum threshold
min_responses = 30

industry_counts = industry_df['industry'].value_counts()
valid_industries = industry_counts[industry_counts >= min_responses].index

industry_df = industry_df[
    industry_df['industry'].isin(valid_industries)
]

# Median salary by industry
industry_salary = (
    industry_df
    .groupby('industry')['converted_comp_yearly']
    .median()
    .sort_values()
    .tail(12)
)

# Plot
plt.figure(figsize=(12,8))

# Horizontal guide lines
plt.hlines(
    y=industry_salary.index,
    xmin=0,
    xmax=industry_salary.values,
    linewidth=2
)

# Dots
plt.scatter(
    industry_salary.values,
    industry_salary.index,
    s=130
)

# Labels
for i, val in enumerate(industry_salary.values):
    plt.text(val + 2000, i, f'${val:,.0f}', va='center')

plt.title('Median Salary by Industry')
plt.xlabel('Median Annual Salary (USD)')
plt.ylabel('Industry')

plt.tight_layout()
plt.savefig('plots/median_sal_industry.png', dpi=300, bbox_inches='tight')
plt.show()

# Salary vs Experience

# Ensure numeric columns
df['converted_comp_yearly'] = pd.to_numeric(
    df['converted_comp_yearly'],
    errors='coerce'
)

df['years_code_pro'] = pd.to_numeric(
    df['years_code_pro'],
    errors='coerce'
)

# Keep valid rows
scatter_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['years_code_pro'] >= 0)
].copy()

# Remove outliers
scatter_df = scatter_df[
    scatter_df['converted_comp_yearly'] <= 300000
]


# Plot
plt.figure(figsize=(12,7))

# Scatter
plt.scatter(
    scatter_df['years_code_pro'],
    scatter_df['converted_comp_yearly'],
    c=scatter_df['converted_comp_yearly'],
    cmap='viridis',
    alpha=0.45,
    s=30
)

# Trend line
z = np.polyfit(
    scatter_df['years_code_pro'],
    scatter_df['converted_comp_yearly'],
    1
)
p = np.poly1d(z)

x_vals = np.linspace(
    scatter_df['years_code_pro'].min(),
    scatter_df['years_code_pro'].max(),
    100
)

y_vals = p(x_vals)

plt.plot(
    x_vals,
    y_vals,
    color='red',
    linewidth=2.5,
    label='Trend Line'
)


for i in range(0, len(x_vals), 12):
    plt.text(
        x_vals[i],
        y_vals[i] + 5000,
        f"{y_vals[i]:,.2f}",
        fontsize=8,
        color='black'
    )

# Tick marks
plt.xticks(
    range(0, int(scatter_df['years_code_pro'].max()) + 1, 2),
    color='black'
)

plt.yticks(
    range(0, 300001, 25000),
    color='black'
)

# Grid
plt.grid(alpha=0.3, linestyle='--')

# Colorbar
cbar = plt.colorbar()
cbar.set_label('Salary Level')
cbar.ax.tick_params(colors='black')

# Labels
plt.title('Salary vs Professional Experience', fontsize=15, fontweight='bold')
plt.xlabel('Years of Professional Experience')
plt.ylabel('Annual Salary (USD)')
plt.legend()

plt.tight_layout(pad=2.0)
plt.savefig('plots/annual_sal_pro_exp.png', dpi=300, bbox_inches='tight')
plt.show()

# SALARY DASHBOARD PREP

# Numeric conversions
df['converted_comp_yearly'] = pd.to_numeric(df['converted_comp_yearly'], errors='coerce')
df['years_code_pro'] = pd.to_numeric(df['years_code_pro'], errors='coerce')




df['education_clean'] = df['ed_level'].replace({
    r".*Primary.*": "Primary school",
    r".*Secondary school.*": "Secondary school",
    r".*Some college.*": "Some college",
    r".*Associate degree.*": "Associate degree",
    r".*Bachelor.*": "Bachelor's degree",
    r".*Master.*": "Master's degree",
    r".*Professional degree.*": "Professional degree",
    r".*Something else.*": "Other"
}, regex=True)

education_order = [
    'Primary school',
    'Secondary school',
    'Some college',
    'Associate degree',
    "Bachelor's degree",
    "Master's degree",
    'Professional degree',
    'Other'
]


# Salary subset

salary_df = df[df['converted_comp_yearly'] > 0].copy()
salary_df_trim = salary_df[salary_df['converted_comp_yearly'] <= 300000].copy()


# 1. Salary Distribution

mean_salary = salary_df_trim['converted_comp_yearly'].mean()
median_salary = salary_df_trim['converted_comp_yearly'].median()


# 2. Log Salary Distribution

salary_df['log_salary'] = np.log10(salary_df['converted_comp_yearly'])


# 3. Median Salary by Experience Band

exp_order = ['0-2 years', '2-5 years', '5-10 years', '10-15 years', '15+ years']
median_salary_exp = (
    df.groupby('exp_band')['converted_comp_yearly']
    .median()
    .reindex(exp_order)
)


# 4. Salary by Education Level

edu_salary = df[
    (df['converted_comp_yearly'] > 0) &
    (df['education_clean'].notna())
].copy()

edu_salary['education_clean'] = pd.Categorical(
    edu_salary['education_clean'],
    categories=education_order,
    ordered=True
)

median_salary_edu = (
    edu_salary.groupby('education_clean', observed=False)['converted_comp_yearly']
    .median()
    .reindex(education_order)
    .dropna()
)


# 5. Top Countries by Median Salary

min_country_responses = 30

country_salary = df[
    (df['converted_comp_yearly'] > 0) &
    (df['country'].notna())
].copy()

country_counts = country_salary['country'].value_counts()
valid_countries = country_counts[country_counts >= min_country_responses].index

median_country_salary = (
    country_salary[country_salary['country'].isin(valid_countries)]
    .groupby('country')['converted_comp_yearly']
    .median()
    .sort_values(ascending=True)
    .tail(10)
)


# 6. Salary by Developer Role

min_role_responses = 40

role_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['dev_type'].notna())
].copy()

role_df['dev_type'] = role_df['dev_type'].str.split(';')
role_df = role_df.explode('dev_type')
role_df['dev_type'] = role_df['dev_type'].str.strip()

role_counts = role_df['dev_type'].value_counts()
valid_roles = role_counts[role_counts >= min_role_responses].index

role_salary = (
    role_df[role_df['dev_type'].isin(valid_roles)]
    .groupby('dev_type')['converted_comp_yearly']
    .median()
    .sort_values()
    .tail(10)
)


# 7. Salary by Industry

min_industry_responses = 30

industry_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['industry'].notna())
].copy()

industry_counts = industry_df['industry'].value_counts()
valid_industries = industry_counts[industry_counts >= min_industry_responses].index

industry_salary = (
    industry_df[industry_df['industry'].isin(valid_industries)]
    .groupby('industry')['converted_comp_yearly']
    .median()
    .sort_values()
    .tail(10)
)


# 8. Salary vs Experience Scatter

scatter_df = df[
    (df['converted_comp_yearly'] > 0) &
    (df['years_code_pro'] >= 0)
].copy()

scatter_df = scatter_df[scatter_df['converted_comp_yearly'] <= 300000]

z = np.polyfit(scatter_df['years_code_pro'], scatter_df['converted_comp_yearly'], 1)
p = np.poly1d(z)

x_vals = np.linspace(scatter_df['years_code_pro'].min(), scatter_df['years_code_pro'].max(), 100)
y_vals = p(x_vals)


# DASHBOARD


fig = plt.figure(figsize=(28, 22))
gs = fig.add_gridspec(4, 3, width_ratios=[1.05, 1.05, 0.95], hspace=0.45, wspace=0.3)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])
ax5 = fig.add_subplot(gs[2, 0])
ax6 = fig.add_subplot(gs[2, 1])
ax7 = fig.add_subplot(gs[3, 0])
ax8 = fig.add_subplot(gs[3, 1])
ax_text = fig.add_subplot(gs[:, 2])

fig.suptitle('Stack Overflow Developer Survey 2023 - Salary Dashboard',
             fontsize=22, fontweight='bold', y=0.995)


# 1. Salary Distribution

ax1.hist(salary_df_trim['converted_comp_yearly'], bins=30, edgecolor='black')
ax1.axvline(mean_salary, linestyle='--', linewidth=2, label=f'Mean: ${mean_salary:,.0f}')
ax1.axvline(median_salary, linestyle='-', linewidth=2, label=f'Median: ${median_salary:,.0f}')
ax1.set_title('Salary Distribution', fontsize=13, fontweight='bold')
ax1.set_xlabel('Annual Salary (USD)')
ax1.set_ylabel('Respondents')
ax1.grid(axis='y', linestyle='--', alpha=0.3)
ax1.legend()


# 2. Log Salary Distribution

ax2.hist(salary_df['log_salary'], bins=30, edgecolor='black')
ax2.set_title('Log Salary Distribution', fontsize=13, fontweight='bold')
ax2.set_xlabel('log10(Annual Salary)')
ax2.set_ylabel('Respondents')
ax2.grid(axis='y', linestyle='--', alpha=0.3)
ax2.set_xticks([4, 4.5, 5, 5.5, 6])
ax2.set_xticklabels(['$10k', '$32k', '$100k', '$316k', '$1M'], color='black')


# 3. Median Salary by Experience Band

ax3.plot(median_salary_exp.index, median_salary_exp.values, marker='o', linewidth=2.5)
for x, y in zip(median_salary_exp.index, median_salary_exp.values):
    if pd.notna(y):
        ax3.text(x, y + 2500, f'${y:,.0f}', ha='center', fontsize=9)
ax3.set_title('Median Salary by Experience Band', fontsize=13, fontweight='bold')
ax3.set_xlabel('Experience Band')
ax3.set_ylabel('Median Salary (USD)')
ax3.grid(axis='y', linestyle='--', alpha=0.3)
ax3.tick_params(axis='x', rotation=20, colors='black')
ax3.tick_params(axis='y', colors='black')


# 4. Salary by Education Level

ax4.plot(median_salary_edu.index, median_salary_edu.values, marker='o', linewidth=2.5)
for x, y in zip(median_salary_edu.index, median_salary_edu.values):
    ax4.text(x, y + 2500, f'${y:,.0f}', ha='center', fontsize=8)
ax4.set_title('Median Salary by Education Level', fontsize=13, fontweight='bold')
ax4.set_xlabel('Education Level')
ax4.set_ylabel('Median Salary (USD)')
ax4.grid(axis='y', linestyle='--', alpha=0.3)
ax4.tick_params(axis='x', rotation=20, colors='black')
ax4.tick_params(axis='y', colors='black')


# 5. Top Countries by Median Salary (Lollipop)

ax5.hlines(y=median_country_salary.index, xmin=0, xmax=median_country_salary.values, linewidth=2)
ax5.scatter(median_country_salary.values, median_country_salary.index, s=120)
for i, val in enumerate(median_country_salary.values):
    ax5.text(val + 2000, i, f'${val:,.0f}', va='center', fontsize=9)
ax5.set_title(f'Top Countries by Median Salary\n(min {min_country_responses} responses)',
              fontsize=13, fontweight='bold')
ax5.set_xlabel('Median Salary (USD)')
ax5.set_ylabel('Country')
ax5.grid(axis='x', linestyle='--', alpha=0.3)


# 6. Salary by Developer Role (Dot Plot)

ax6.scatter(role_salary.values, role_salary.index, s=130)
for y, x in zip(role_salary.index, role_salary.values):
    ax6.plot([0, x], [y, y], linewidth=1.4)
for i, val in enumerate(role_salary.values):
    ax6.text(val + 2000, i, f'${val:,.0f}', va='center', fontsize=9)
ax6.set_title('Median Salary by Developer Role', fontsize=13, fontweight='bold')
ax6.set_xlabel('Median Salary (USD)')
ax6.set_ylabel('Developer Role')
ax6.grid(axis='x', linestyle='--', alpha=0.3)


# 7. Salary by Industry (Cleveland Dot Plot)

ax7.hlines(y=industry_salary.index, xmin=0, xmax=industry_salary.values, linewidth=2)
ax7.scatter(industry_salary.values, industry_salary.index, s=120)
for i, val in enumerate(industry_salary.values):
    ax7.text(val + 2000, i, f'${val:,.0f}', va='center', fontsize=9)
ax7.set_title('Median Salary by Industry', fontsize=13, fontweight='bold')
ax7.set_xlabel('Median Salary (USD)')
ax7.set_ylabel('Industry')
ax7.grid(axis='x', linestyle='--', alpha=0.3)


# 8. Salary vs Experience Scatter

scatter = ax8.scatter(
    scatter_df['years_code_pro'],
    scatter_df['converted_comp_yearly'],
    c=scatter_df['converted_comp_yearly'],
    cmap='viridis',
    alpha=0.45,
    s=25
)

ax8.plot(x_vals, y_vals, color='red', linewidth=2.5, label='Trend Line')

for i in range(0, len(x_vals), 12):
    ax8.text(
        x_vals[i],
        y_vals[i] + 5000,
        f'{y_vals[i]:,.2f}',
        fontsize=8,
        color='black'
    )

ax8.set_title('Salary vs Professional Experience', fontsize=13, fontweight='bold')
ax8.set_xlabel('Years of Professional Experience')
ax8.set_ylabel('Annual Salary (USD)')
ax8.set_xticks(range(0, int(scatter_df['years_code_pro'].max()) + 1, 2))
ax8.set_yticks(range(0, 300001, 25000))
ax8.tick_params(axis='x', colors='black')
ax8.tick_params(axis='y', colors='black')
ax8.grid(alpha=0.3, linestyle='--')
ax8.legend()

cbar = fig.colorbar(scatter, ax=ax8, fraction=0.046, pad=0.04)
cbar.set_label('Salary Level')
cbar.ax.tick_params(colors='black')


# INSIGHTS PANEL

ax_text.axis('off')

insight_text = f"""
Salary Dashboard Insights

1. Distribution
Salary is strongly right skewed.
A relatively small group of high earners
pulls the mean above the median.

2. Log distribution
The log-scale histogram reveals the
main body of the salary distribution
more clearly than the raw histogram.

3. Experience effect
Median salary rises with experience,
confirming that professional tenure is
one of the strongest salary drivers.

4. Education effect
Higher education groups may show
higher median pay, but differences are
smaller than the effect of experience.

5. Country effect
Country-level pay differences remain
substantial even after applying a minimum
response threshold of 100.

6. Role effect
Developer roles show meaningful salary
variation, suggesting specialization and
market demand influence compensation.

7. Industry effect
Industry context matters: some sectors
offer materially higher median pay than
others.

8. Scatter relationship
The scatter plot shows a positive salary-
experience relationship, though variation
within each experience level remains high.

Overall takeaway
Compensation is shaped by multiple factors:
experience, geography, role, and industry.
Median-based analysis is preferred here
because salary data contains strong outliers.
"""

ax_text.text(
    0, 1, insight_text,
    va='top',
    fontsize=12,
    linespacing=1.5,
    bbox=dict(boxstyle='round,pad=0.7', facecolor='whitesmoke', edgecolor='gray')
)

plt.tight_layout(rect=[0, 0, 1, 0.98])
plt.savefig('plots/salary_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()

"""SECTION 5- WORK STYPE & PROFESSIONAL ENVIRONMENT"""

""" Remote vs Hybrid vs On-site"""


# Clean remote_work labels


df['remote_work_clean'] = df['remote_work'].replace({
    'Remote': 'Remote',
    'Hybrid (some remote, some in-person)': 'Hybrid',
    'In-person': 'On-site'
})

remote_order = ['Remote', 'Hybrid', 'On-site']

remote_dist = (
    df['remote_work_clean']
    .value_counts()
    .reindex(remote_order)
)

plt.figure(figsize=(10,6))

plt.figure(figsize=(10,6))

plt.barh(
    remote_dist.index,
    remote_dist.values
)

plt.title('Remote vs Hybrid vs On-site Work')
plt.xlabel('Number of Respondents')
plt.ylabel('Work Arrangement')

for i, v in enumerate(remote_dist.values):
    if pd.notna(v):
        plt.text(v + max(remote_dist.values)*0.01, i, str(int(v)), va='center')

plt.tight_layout()
plt.show()

""" Remote work by Experience band"""

# Remote Work by Experience Band


# Ensure exp_band exists
df['exp_band'] = df['years_code_pro'].apply(exp_band)

# Order for experience bands
exp_order = ['0-2 years', '2-5 years', '5-10 years', '10-15 years', '15+ years']


remote_exp = pd.crosstab(
    df['exp_band'],
    df['remote_work_clean']
).reindex(exp_order)


remote_exp = remote_exp.fillna(0)


# Stacked Bar Chart

remote_exp.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6),
    width=0.8
)

plt.title('Remote Work by Experience Band')
plt.xlabel('Experience Band')
plt.ylabel('Number of Respondents')
plt.xticks(rotation=0)

plt.legend(title='Work Type', bbox_to_anchor=(1.02,1), loc='upper left')

plt.tight_layout()
plt.savefig('plots/work_type.png', dpi=300, bbox_inches='tight')
plt.show()

# Correlation Heatmap
# Relationships Between Key Developer Features


# 1. Ensure tech_count exists

df['tech_count'] = (
    df['language_have_worked_with']
    .fillna('')
    .apply(lambda x: len([i for i in x.split(';') if i.strip() != '']))
)


# 2. Education Level Ranking

# If education_clean already exists then use it.
# Otherwise create it from ed_level.

if 'education_clean' not in df.columns:
    df['education_clean'] = df['ed_level'].replace({
        r'.*Primary.*': 'Primary school',
        r'.*Secondary school.*': 'Secondary school',
        r'.*Some college.*': 'Some college',
        r'.*Associate.*': 'Associate degree',
        r'.*Bachelor.*': "Bachelor's degree",
        r'.*Master.*': "Master's degree",
        r'.*Professional degree.*': 'Professional degree',
        r'.*Something else.*': 'Other'
    }, regex=True)

education_rank = {
    'Primary school': 1,
    'Secondary school': 2,
    'Some college': 3,
    'Associate degree': 4,
    "Bachelor's degree": 5,
    "Master's degree": 6,
    'Professional degree': 7,
    'Other': np.nan
}

df['education_num'] = df['education_clean'].map(education_rank)


# 3. Remote Work Encoding

remote_rank = {
    'On-site': 1,
    'Hybrid': 2,
    'Remote': 3
}

df['remote_num'] = df['remote_work_clean'].map(remote_rank)


# 4. Country Rank by Median Salary

country_salary = (
    df.groupby('country')['converted_comp_yearly']
    .median()
    .sort_values(ascending=False)
)

country_rank_map = {
    country: rank + 1
    for rank, country in enumerate(country_salary.index)
}

df['country_rank'] = df['country'].map(country_rank_map)


# 5. Select Variables

corr_df = df[[
    'converted_comp_yearly',
    'years_code_pro',
    'tech_count',
    'education_num',
    'remote_num',
    'country_rank'
]].copy()

corr_df.columns = [
    'Salary',
    'Experience',
    'Tech Count',
    'Education',
    'Remote Work',
    'Country Rank'
]


# 6. Correlation Matrix

corr = corr_df.corr()


# 7. Heatmap Plot

plt.figure(figsize=(10,8))

sns.heatmap(
    corr,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    linewidths=1,
    square=True,
    cbar_kws={'shrink':0.8}
)

plt.title('Correlation Heatmap of Developer Features', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('plots/Heatmap_dev_features.png', dpi=300, bbox_inches='tight')
plt.show()

# Country Opportunity Index
# Rank Best Countries for Developers


# 1. Ensure tech_count exists

df['tech_count'] = (
    df['language_have_worked_with']
    .fillna('')
    .apply(lambda x: len([i for i in x.split(';') if i.strip() != '']))
)


# 2. Keep valid rows

country_df = df.copy()


# 3. Aggregate Country Metrics

country_metrics = country_df.groupby('country').agg(
    median_salary=('converted_comp_yearly', 'median'),
    remote_pct=('remote_work_clean', lambda x: (x == 'Remote').mean() * 100),
    avg_tech_count=('tech_count', 'mean'),
    respondents=('country', 'size')
).reset_index()


# 4. Minimum response threshold

country_metrics = country_metrics[country_metrics['respondents'] >= 100]


# 5. Fill Missing Values

country_metrics['median_salary'] = country_metrics['median_salary'].fillna(
    country_metrics['median_salary'].median()
)

country_metrics['remote_pct'] = country_metrics['remote_pct'].fillna(0)
country_metrics['avg_tech_count'] = country_metrics['avg_tech_count'].fillna(
    country_metrics['avg_tech_count'].median()
)


# 6. Normalize Metrics (0 to 1)

def minmax(series):
    return (series - series.min()) / (series.max() - series.min())

country_metrics['salary_score'] = minmax(country_metrics['median_salary'])
country_metrics['remote_score'] = minmax(country_metrics['remote_pct'])
country_metrics['tech_score'] = minmax(country_metrics['avg_tech_count'])
country_metrics['volume_score'] = minmax(country_metrics['respondents'])


# 7. Weighted Opportunity Index


country_metrics['opportunity_index'] = (
      0.40 * country_metrics['salary_score']
    + 0.25 * country_metrics['remote_score']
    + 0.20 * country_metrics['tech_score']
    + 0.15 * country_metrics['volume_score']
)


# 8. Rank Countries

country_metrics = country_metrics.sort_values(
    by='opportunity_index',
    ascending=False
)

print(country_metrics[['country', 'opportunity_index']].head(15))

# Bubble Chart

top_n = 20
plot_df = country_metrics.head(top_n).copy()

plt.figure(figsize=(14,8))

scatter = plt.scatter(
    plot_df['median_salary'],
    plot_df['remote_pct'],
    s=plot_df['respondents'] * 6,
    c=plot_df['opportunity_index'],
    alpha=0.75
)

# Labels
for _, row in plot_df.iterrows():
    plt.text(
        row['median_salary'] * 1.01,
        row['remote_pct'] + 0.3,
        row['country'],
        fontsize=9
    )

plt.colorbar(label='Opportunity Index')

plt.title('Top Countries by Developer Opportunity Index', fontsize=16, fontweight='bold')
plt.xlabel('Median Salary')
plt.ylabel('Remote Work %')
plt.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('plots/top_countries_by_oppIdx.png', dpi=300, bbox_inches='tight')
plt.show()



